definitions:
  onlineSubscriptions_internal_models.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      user_id:
        type: string
    type: object
  onlineSubscriptions_internal_models.SubscriptionRequest:
    properties:
      end_date:
        type: string
      name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Api for handling subscriptions
  title: Subscription api
  version: "1.0"
paths:
  /api/subscriptions:
    get:
      description: Get a page of subscriptions
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: amount of entries in page
        in: query
        name: perPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/onlineSubscriptions_internal_models.Subscription'
            type: array
      summary: List subscription page
      tags:
      - subscription
  /api/subscriptions/{id}:
    delete:
      description: Deletes a subscription
      parameters:
      - description: subscription id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a subscription
      tags:
      - subscription
    get:
      description: Get a single subscription by ID
      parameters:
      - description: subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/onlineSubscriptions_internal_models.Subscription'
      summary: Get subscription by id
      tags:
      - subscription
    put:
      description: Updates a subscription
      parameters:
      - description: subscription id
        in: path
        name: id
        required: true
        type: string
      - description: subscription request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/onlineSubscriptions_internal_models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Update a subscription
      tags:
      - subscription
  /api/subscriptions/create:
    post:
      description: Creates a subscription
      parameters:
      - description: subscription request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/onlineSubscriptions_internal_models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a subscription
      tags:
      - subscription
  /api/subscriptions/sum:
    get:
      description: Calculates a sum price of subscriptions for user between dates
      parameters:
      - description: subscription user id
        in: query
        name: user_id
        type: string
      - description: subscription name
        in: query
        name: subscription_name
        type: string
      - description: subscription start date from
        in: query
        name: date_from
        type: string
      - description: subscription start date to
        in: query
        name: date_to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Calculate a sum price of subscriptions
      tags:
      - subscription
swagger: "2.0"
